### ISSUE TITLE
syb fails to compile with ghc 9.0.1 (alpha)

### ISSUE THREAD

**Issue by GeorgeCo** [dreixel/syb#27]
cabal install syb --allow-new
...
[ 7 of 16] Compiling Data.Generics.Twins ( src/Data/Generics/Twins.hs, dist/build/Data/Generics/Twins.o, dist/build/Data/Generics/Twins.dyn_o )

src/Data/Generics/Twins.hs:290:58: error:
    • Couldn't match type: b0 -> Ordering
                     with: forall a3. Data a3 => a3 -> Ordering
      Expected: a2 -> GenericQ Ordering
        Actual: a2 -> b0 -> Ordering
    • In the first argument of ‘gzipWithQ’, namely ‘gcompare'’
      In the first argument of ‘mconcat’, namely
        ‘(gzipWithQ gcompare' x y)’
      In the second argument of ‘mappend’, namely
        ‘mconcat (gzipWithQ gcompare' x y)’
    |
290 |             nX `compare` nY `mappend` mconcat (gzipWithQ gcompare' x y)
    |                                                          ^^^^^^^^^
cabal: Failed to build syb-0.7.1. See the build log above for details.

**Comment by GeorgeCo** [comment]
issue is still true with ghc 9.0 rc1

**Comment by amesgen** [comment]
This has been resolved by #25, or am I missing sth?

**Comment by konn** [comment]
The current master branch compiles with GHC 9.0.1 on my environment (macOS), great!
By the way, is there any schedule for uploading a new version with GHC 9 support on Hackage?

**Comment by amesgen** [comment]
`0.7.2.1` has been released with GHC 9 compat: https://hackage.haskell.org/package/syb-0.7.2.1

**Comment by konn** [comment]
Great, thanks!

**Comment by andreasabel** [comment]
Issue can be closed.
