### ISSUE TITLE
syb fails to compile with ghc-9.6

### ISSUE THREAD

**Issue by TristanCacqueray** [dreixel/syb#40]
Building with latest GHC seems to produce this error:

```
tests/Tree.hs:51:14: error: [GHC-88464]
    Variable not in scope: guard :: Bool -> Maybe a0
   |
51 |           do guard (glength x == length ts)
   |  
```

**Comment by sergv** [comment]
Fixed veersion released as `0.7.2.3`.
